export const data = [
  {
    name: "Photo 1",
    url: "img/nature1.jpg",
    description: "photo 1 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 2",
    url: "img/water2.jpg",
    description: "photo 2 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 3",
    url: "img/road3.jpg",
    description: "photo 3 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 4",
    url: "img/waterfall4.jpg",
    description: "photo 4 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 5",
    url: "img/sunset5.jpg",
    description: "photo 5 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 6",
    url: "img/colorsky6.jpg",
    description: "photo 6 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 7",
    url: "img/sunset7.jpg",
    description: "photo 7 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 8",
    url: "img/waterfall8.jpg",
    description: "photo 8 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
  {
    name: "Photo 9",
    url: "img/colorsky9.jpg",
    description: "photo 9 description",
    date: "2023-11-27",
    type: "image/jpg",
  },
];